<h1>Login</h1>
<?php if (!empty($this->error)): ?>
  <div class="error"><?= htmlspecialchars($this->error) ?></div>
<?php endif; ?>
<form method="POST" action="<?= $this->baseUrl() ?>/user/login">
    <div>
      <label>Username</label>
      <input type="text" name="username" required>
    </div>
    <div>
      <label>Password</label>
      <input type="password" name="password" required>
    </div>
    <button type="submit">Login</button>
</form>
<p>No account yet? 
<a href="<?= $this->baseUrl() ?>/user/register">Register here</a>
</p>