<h1>Register</h1>
<?php if ($this->error): ?>
  <div class="error"><?= htmlspecialchars($this->error) ?></div>
<?php endif; ?>
<form method="POST" action="/user/register">
    <div>
      <label>Username</label>
      <input type="text" name="username" required/>
    </div>
    <div>
      <label>Password</label>
      <input type="password" name="password" required/>
    </div>
    <button type="submit">Register</button>
</form>
<p>Already have an account? 
<a href="/user/login">Login here</a>
</p>