<h1>New task</h1>

<!-- <form action="/tasks/create" method=“POST"> -->
<form action="http://todo.local/tasks/create" method="POST">
<input type="text" name="name">
<input type="text" name="description">
<select name="status">
    <option value="">All statuses</option>
    <option value="pending">Pending</option>
    <option value="in_progress">In progress</option>
    <option value="completed">Completed</option>
</select>
<input type="text" name="end_time">
<button type="submit">Create task</button>
</form>

<a href="/tasks">Back to dashboard</a>
