<h1>New task</h1>

<form action="/tasks/create" method="POST">
<input type="text" name="name">
<input type="text" name="description">
<select name="status">
    <option value="pending">Pending</option>
    <option value="in_progress">In progress</option>
    <option value="completed">Completed</option>
    <option value="">All statuses</option>
</select>
<input type="datetime-local" name="end_time" value="<?= $this->task['end_time'] ?>">
<button type="submit">Create task</button>
</form>

<a href="/dashboard">Back to dashboard</a>
