<h1>My tasks</h1>
<a href="<?= $this->baseUrl() ?>/tasks/create">Create task</a>
<a href="<?= $this->baseUrl() ?>/user/logout">Logout</a>
<form action="<?= $this->baseUrl() ?>/dashboard" method="GET">
<input name="search" type="text">
<select name="status">
    <option value="">All statuses</option>
    <option value="pending">Pending</option>
    <option value="in_progress">In progress</option>
    <option value="completed">Completed</option>
</select>
<button type="submit">Search</button>
<a href="<?= $this->baseUrl() ?>/tasks">Clear filters</a>
<a href="<?= $this->baseUrl() ?>/tags">Manage Tags</a>

</form>
<ul>
<?php foreach ($this->tasks as $task): ?>
    <li>
    <?= $task['name'] ?>
    <?= substr($task['description'], 0, 50) ?>
    <?= $task['status'] ?>
    <a href="/tasks/edit/<?= $task['id'] ?>">View</a>
    <a href="/tasks/delete/<?= $task['id'] ?>">Delete</a>
    </li>
<?php endforeach; ?>
</ul>